package utils

const (
	CPU_CORES_CPUINFO_ERROR = -2
	LAVG_TREND_CPUINFO_ERROR = -1
	LAVG_TREND_ERROR = 0
	LAVG_TREND_INCREASING = 1
	LAVG_TREND_NORMAL = 2
	LAVG_LOAD_LEVEL_YELLOW = 70
	DEL_FILE_LIST_E_SLEEP = 60
)

